<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Sifteo</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="JsonFx">
      <HintPath>../../extracted/siftrunner/Siftrunner.app/Contents/Resources/Runtimes/Mono/Current/sifteo/JsonFx.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../../../../../usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>